# Generated by Django 2.2.5 on 2019-11-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nick_name',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
